language: python

python:
  - "2.7"

env:
  - DJANGO="https://www.djangoproject.com/download/1.7c2/tarball/"
  - DJANGO="django==1.6.8"
  - DJANGO="django==1.5.11"

install:
  - pip install $DJANGO
  - pip install celery==3.1.16
  - pip install django-celery==3.1.16

script:
  - python runtests.py
  - python runtests-djcelery.py

notifications:
  email:
    recipients:
      - nicolas.grasset@gmail.com
    on_success: change
    on_failure: change
